name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - name: Set up msbuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Build with msbuild
        run: |
          msbuild LR2HackBox.sln /t:Build /p:Configuration=Release /p:Platform=x86

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: bin/Release/azop.dll